// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHERtwpEresAA5yxgM92bv9dmJQmCRzc',
    appId: '1:601096685939:web:4432afaadb1ff183ccdd06',
    messagingSenderId: '601096685939',
    projectId: 'thigiuaky-bf69f',
    authDomain: 'thigiuaky-bf69f.firebaseapp.com',
    storageBucket: 'thigiuaky-bf69f.appspot.com',
    measurementId: 'G-6MC9QCV1LH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAag3_gRIbRwLdE0D7e6c13RaTDs3beydo',
    appId: '1:601096685939:android:7fa9e5288c18d5e8ccdd06',
    messagingSenderId: '601096685939',
    projectId: 'thigiuaky-bf69f',
    storageBucket: 'thigiuaky-bf69f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA3-J6D3IslqvXi9RU0_dGNymgyYlZZnA',
    appId: '1:601096685939:ios:adf0b3e9067c996eccdd06',
    messagingSenderId: '601096685939',
    projectId: 'thigiuaky-bf69f',
    storageBucket: 'thigiuaky-bf69f.appspot.com',
    iosBundleId: 'com.example.bookinghotel',
  );
}
